version: '3.1'
#
# Teamspeak 3 server
# Example: for deployment on a server with a dedicated IP address
#
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: always
    volumes:
      - "./data/teamspeak:/var/ts3server/"
      #- "./licensekey.dat:/var/ts3server/licensekey.dat"
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: 123456789
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
  db:
    image: mariadb
    container_name: teamspeak-db
    restart: always
    ports:
      - 53306:3306
    volumes:
      - "./data/teamspeak-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: teamspeak