version: "3" #This is the docker-compose version, NOT the projektversion
services:
  cron:
    image: lfs96/cron:latest
    volumes:
      - ./crontabs/:/etc/crontabs/
    restart: always
    environment:
      - com.centurylinklabs.watchtower.enable=false
    networks:
      - claninterface
  claninterface_mysql:
    image: "mariadb"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=claninterface
    restart: always
    networks:
      - claninterface
  claninterface_amp:
    image: lfs96/wot-claninterface-1fp:latest
    restart: always
    depends_on:
      - claninterface_mysql
      - cron
    ports:
      - "127.0.0.1:1080:80"  # nginx reverse Proxy
      - "127.0.0.1:1443:443" # nginx reverse Proxy
      # - "80:80"    # standalone
      # - "443:443"  # standalone
    env_file: .env
    networks:
      - claninterface
      - teamspeak_default
      - nginx_proxy_default
    #network_mode: host

networks:
  claninterface:
    driver: bridge
  teamspeak_default:
    external: true
  nginx_proxy_default:
    external: true


