version: "3" #This is the docker-compose version, NOT the projektversion
services:
  claninterface_amp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        branch: main
    ports:
      - "1080:80"  # nginx reverse Proxy
      - "1443:443" # nginx reverse Proxy
      # - "80:80"    # standalone
      # - "443:443"  # standalone
    env_file: .env
    networks:
      - claninterface
    volumes:
      - ./ClanInterface/config:/var/www/html/config
      - ./ClanInterface/src:/var/www/html/src
      - ./ClanInterface/webroot:/var/www/html/webroot
      - ./ClanInterface/templates:/var/www/html/templates
      - ./ClanInterface/logs:/var/www/html/logs
  cron:
    image: lfs96/cron:latest
    volumes:
      - ./crontabs/:/etc/crontabs/
    networks:
      - claninterface
  claninterface_mysql:
    image: "mariadb"
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=claninterface
    networks:
      - claninterface
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_PLUGINS=tables-filter tinymce
    ports:
      - 8080:8080
    networks:
      - claninterface
networks:
  claninterface:
    driver: bridge
